[phases.setup]

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "DATABASE_URL=postgres://actioncash:Rlb8TaB3hI6yz4s7egXqgBg5ieDO4jkzHmy209wzMGBGlccD2B3kABy9jtaH4Uen@im5bgzdog99g2xbxnl7rx2x5:5432/actioncash node scripts/prisma-provider.js && DATABASE_URL=postgres://actioncash:Rlb8TaB3hI6yz4s7egXqgBg5ieDO4jkzHmy209wzMGBGlccD2B3kABy9jtaH4Uen@im5bgzdog99g2xbxnl7rx2x5:5432/actioncash npx prisma generate && npm run build"

[variables]
DATABASE_URL = 'postgres://actioncash:Rlb8TaB3hI6yz4s7egXqgBg5ieDO4jkzHmy209wzMGBGlccD2B3kABy9jtaH4Uen@im5bgzdog99g2xbxnl7rx2x5:5432/actioncash'
JWT_SECRET = 'a7f3e9b1c4d6f8a2e5b7c9d1f3a5e7b9c2d4f6a8e1b3c5d7f9a2e4b6c8d1f3a5'
